---
- name: Send ntfy notification from demo-1
  hosts: 192.168.178.69
  become: true
 
  tasks:
    - name: Send ntfy notification
      shell: curl -d "This is a test notification from demo-1" https://ntfy.dianndserver.duckdns.org/phone