---
- name: Send ntfy notification from demo-1
  hosts: 192.168.178.69
  become: true
  vars:
    ntfy_url: "https://ntfy.dinandserver.duckdns.org/phone"
    ntfy_message: "This is a test notification from demo-1"
  tasks:
    - name: Send ntfy notification
      shell: curl -d "{{ ntfy_message }}" {{ ntfy_url }}