---
- name: Send a ntfy notification from demo-1
  hosts: demo-1
  become: true
  tasks:
    - name: Send ntfy notification
      ansible.builtin.command:
        cmd: curl -d "This is a test notification from demo-1" https://ntfy.dinandserver.duckdns.org/phone